apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      chapter: sdev372
  template:
    metadata:
      labels:
        chapter: sdev372
    spec:
      containers:
        - name: music-project
          image: danzzilla/music-project
          ports:
            - containerPort: 8080