apiVersion: v1
kind: Pod
metadata:
  name: music-project-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: music-project
      image: danzzilla/music-project
      ports:
        - containerPort: 8080